<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>ZYRON Print</AssemblyName>
    <RootNamespace>Zyron.Print</RootNamespace>
    <Version>0.1.1</Version>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\zyron-print.ico</ApplicationIcon>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="Assets\zyron-print-icon.png" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
